variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

stages:
- stage: Build
  pool:
    vmImage: '$(buildAgent)'

  jobs:
  - job: Build
    workspace:
      clean: all

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\OtherTests.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '**\WinAppDriverExample\bin\Release'
        ArtifactName: 'uiTests'
        publishLocation: 'Container'

- stage: Run_UI_tests
  dependsOn: Build
#  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  pool:
    vmImage: '$(uiTestAgent)'

  jobs:
  - job: Run_WinAppDriver_Tests
    workspace:
     clean: all

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'start ''$(winAppDriverPath)'''

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\WinAppDriverExample.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        uiTests: true
        testRunTitle: 'WinAppDriverExample UI Tests'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'get-process "WinAppDriver" | stop-process -force'